name: Hello Wor
on:
  pull_request:
    types: [opened]
jobs:
  startup:
    name: Run startup script
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
  build:
    name: Here is my build task
    runs-on: ubuntu-latest
    needs: startup
    steps:
      - name: Comment on PR
        run: gh pr comment "${{ github.event.pull_request.html_url }}" --body "Thanks for your PR. We will review shortly! "
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Prepare script
        run: ./.github/script/checker.sh
        env:
          FILE: ./src/components/Button.js
      - name: Merge Code
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout main
          git merge ${{ github.head_ref }} --no-ff --no-edit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Comment on PR
        run: gh pr comment "${{ github.event.pull_request.html_url }}" --body "Thanks for your PR. The code has been merge!"